Add features from base-images repo
tiiuae/fog-ros-baseimage pull request #6
Opened 2022-05-17 09:35 UTC by lassilaiho

Adds features from base images in https://github.com/tiiuae/base-images. Those images will be deprecated in favor of the images in this repo.

2022-05-17 14:33 UTC, joonas-fi requested changes

2022-05-17 14:33 UTC, joonas-fi commented on Dockerfile.builder
> +ENV BASH_ENV="/opt/ros/$ROS_DISTRO/setup.bash" \
Are these required at the builder side? If so, could be commented which process/component in the compilation process uses these

2022-05-17 14:33 UTC, joonas-fi commented on Dockerfile
> +ARG ROS_DISTRO
This is already defined here https://github.com/tiiuae/fog-ros-baseimage/blob/8cac3e3148426e6834216e3a0d9e76237e1d8838/Dockerfile#L1

2022-05-18 11:39 UTC, lassilaiho commented on Dockerfile
> +RUN echo "source /opt/ros/$ROS_DISTRO/setup.bash" >> /etc/bash.bashrc && \
I tested it a bit more and the `RMW_IMPLEMENTATION` part on line 45 is superfluous. Setting the `BASH_ENV` variable to the ROS setup script instructs Bash to source the script on startup, which means that RUN commands don't have to include a line for sourcing the ROS environment in case they need it. This is a Bash-specific feature, so line 41 is needed to set the default shell for RUN commands to Bash (by default it is sh). Interactive Bash shells don't source the file pointed to by `BASH_ENV`, but instead source `/etc/bash.bashrc`, so it is configured to source the ROS environment as well. This way the ROS environment is sourced automatically when opening a Bash shell in a container for e.g. debugging.

2022-05-18 11:39 UTC, lassilaiho commented on Dockerfile.builder
> +ENV BASH_ENV="/opt/ros/$ROS_DISTRO/setup.bash" \
The rclgo message binding generation depends on the ROS environment being sourced so that it can find the ROS message definitions. Regarding the `RMW_IMPLEMENTATION` part, I think at some point there was some problem with programs using rclgo linking to Cyclone DDS middleware by default and then not working correctly with Fast-DDS, so the `RMW_IMPLEMENTATION` is set during the build process as well.

2022-05-18 11:48 UTC, lassilaiho commented on Dockerfile
> +ARG ROS_DISTRO
The line is now removed.

2022-05-19 07:28 UTC, joonas-fi commented on Dockerfile.builder
> +ENV BASH_ENV="/opt/ros/$ROS_DISTRO/setup.bash" \
Ok. Thanks for adding the code comment :+1:  makes it easier later when we forget why, to know why it's needed

2022-05-19 07:36 UTC, joonas-fi commented on Dockerfile
> +RUN echo "source /opt/ros/$ROS_DISTRO/setup.bash" >> /etc/bash.bashrc && \
I like the fact that if you exec into the container with shell for debugging, that we now get the ROS environment set. :+1: 

A small concern, I'm not sure if it's an issue but does this mean that when we launch ROS nodes with `ros-with-env.sh`, the ROS `setup.bash` gets sourced twice? Once by Bash, once explicitly: https://github.com/tiiuae/fog-ros-baseimage/blob/78028078be2fff2b8e850f8ef1f2842a05dfe4f8/ros-with-env.sh#L18

I think it can lead to adding linker include paths twice etc.

I leave it up to you to decide if that's an issue or not. Otherwise, this PR LGTM!

2022-05-19 07:36 UTC, joonas-fi approved these changes

2022-05-19 08:23 UTC, lassilaiho commented on Dockerfile
> +RUN echo "source /opt/ros/$ROS_DISTRO/setup.bash" >> /etc/bash.bashrc && \
I think it is safe to source the ROS setup script twice. For example the script checks for duplicate paths before adding them to e.g. `PATH` and `AMENT_PREFIX_PATH`.

2022-05-19 08:25 UTC, merged